export default {
  slug: "codex",
  name: "codex",
  docFolder: "codex",
  categoryLabel: "终端型 Agent Runtime",
  badgeText: "turn context + 启动期记忆管线",
  plainIntro:
    "codex 把 context、memory、state/history 拆成不同职责层：每个 turn 负责组装可见上下文，memory 走启动期两阶段管线，SQLite 和文件系统分别承担结构化持久化与同步。",
  summary:
    "要读懂 codex，关键不是看“有没有 memory”，而是先分清 turn context、thread history、memory pipeline 和 SQLite state 这四层。",
  whatTheModelSees: [
    "模型拿到的是经过 ContextManager 规范化后的 turn 历史，不是原始聊天记录。",
    "首次 turn 通常是全量注入；后续 turn 主要基于 reference_context_item 做增量更新。",
    "build_initial_context() 会把模型切换、权限、developer instructions、memory prompt、协作模式、人格、应用/技能、用户指令和环境等一起注入。",
    "clone_history().for_prompt() 才是最终送进模型的 prompt 历史。",
    "compact 或 rollback 之后，模型看到的是重建后的窗口身份，而不是简单删减后的旧历史。",
    "realtime 启动时会走另一条 startup context 路径，并排除 memory summaries 和 AGENTS 聚合内容。",
    "memory tool 只读 memory_summary.md，不会直接扫完整 memories/ 目录。",
  ],
  contextBlocks: [
    { title: "turn 上下文管理", summary: "ContextManager 负责规范化、截断、回卷和补齐 turn 历史。", kind: "runtime" },
    { title: "全量与增量上下文", summary: "reference_context_item 决定首次全量注入还是后续只注入 settings diff。", kind: "strategy" },
    { title: "初始上下文构成", summary: "build_initial_context() 把环境、权限、指令、人格、插件与协作模式一次性拼装进上下文。", kind: "composition" },
    { title: "memory 启动管线", summary: "memory 不是单一数据库，而是 phase1 / phase2 的启动期流水线。", kind: "pipeline" },
    { title: "压缩与实时启动", summary: "compact 重建窗口身份，realtime_context 走独立 startup context 路径。", kind: "boundary" },
    { title: "持久化分层", summary: "SQLite、history.jsonl 和 memories/ 分别承担结构化状态、全局历史和记忆产物。", kind: "storage" },
  ],
  assemblyFlow: [
    "run_turn() 启动一次 turn。",
    "record_context_updates_and_set_reference_context_item() 记录上下文更新，并决定这次是全量还是增量。",
    "ContextManager 先做 normalize，过滤非 API item，补齐 tool call/output，去掉 orphan output 和不支持模型中的 image 内容。",
    "clone_history().for_prompt() 生成真正要送进模型的历史上下文。",
    "模型采样时，window_generation 和 x-codex-window-id 维持窗口身份。",
    "如果触发 compact 或 rollback，就重写 history 并重新注入 initial context。",
    "realtime 场景会改走 realtime_context，按独立路径组装 startup context。",
  ],
  memoryLifecycle: [
    "仅在 ephemeral、启用 MemoryTool、且不是 subagent root session 时启动 memory startup。",
    "start_memories_startup_task() 拉起整个记忆管线。",
    "phase1 先 claim startup jobs，再 build request context，并行做 extraction。",
    "phase1 把 rollout_summary、rollout_slug、raw_memory 等结果写入 state DB 的 stage1_outputs。",
    "phase2 再 claim global consolidation job，读取筛选后的输入，启动 MemoryConsolidation agent 做全局 consolidation。",
    "phase2 将结果同步到 codex_home/memories/，并更新 raw_memories.md / summaries。",
    "发生 fresh start 时，会清 state DB 和记忆目录，并可把已有 thread 的 memory_mode 关掉。",
  ],
  storageLayers: [
    "CODEX_SQLITE_HOME/state_5.sqlite：结构化运行态，重点是 threads、stage1_outputs、jobs、thread_spawn_edges 和 memory_mode。",
    "CODEX_SQLITE_HOME/logs_2.sqlite：日志层，和结构化 state 分开。",
    "codex_home/history.jsonl：全局 append-only 历史文件，更像审计流，不等于 state。",
    "codex_home/memories/：记忆产物落盘与同步的文件系统层。",
    "codex_home/memories/memory_summary.md：memory tool 的读取入口，是摘要层，不是全量 memory root。",
    "stage1_outputs / jobs：记忆生命周期里的中间状态层，承载抽取结果、租约和 watermark。",
  ],
  commonMistakes: [
    "把 ContextManager 误认为原始聊天日志容器。",
    "把 history.jsonl 误认为 SQLite state。",
    "把 memories/ 误认为唯一真相，忽略 stage1_outputs 和 jobs 也保存记忆生命周期信息。",
    "把 memory_summary.md 误认为完整记忆目录。",
    "把 realtime startup context 和普通 turn context 混成同一条链路。",
  ],
  readerTakeaways: [
    "context、memory、state/history 是四层不同职责，不是同一个东西的不同叫法。",
    "reference_context_item 和 window_generation 是理解上下文切换的两个核心锚点。",
    "最先读 02-context管理 和 03-memory实现，再回看 04-存储与状态，最容易建立整体模型。",
  ],
  sourceAnchors: [
    { path: "docs/codex.md", start: 5, end: 5, note: "三层定位：core / state / core/memories" },
    { path: "docs/codex.md", start: 31, end: 31, note: "总结 turn context、增量更新、memory pipeline、state/history 分层" },
    { path: "docs/codex.md", start: 53, end: 55, note: "建议先读 context 管理，再读 memory 实现" },
    { path: "docs/codex/01-架构与范围.md", start: 5, end: 6, note: "三层实现与职责边界" },
    { path: "docs/codex/01-架构与范围.md", start: 15, end: 20, note: "范围边界：core/state/cli 与 sdk 说明" },
    { path: "docs/codex/01-架构与范围.md", start: 28, end: 29, note: "ContextManager、history.jsonl、memories、memory tool 的关键边界" },
    { path: "docs/codex/02-context管理.md", start: 5, end: 5, note: "ContextManager 保存并规范化 turn 历史" },
    { path: "docs/codex/02-context管理.md", start: 13, end: 15, note: "reference_context_item 决定全量与增量" },
    { path: "docs/codex/02-context管理.md", start: 21, end: 35, note: "build_initial_context() 的注入构成" },
    { path: "docs/codex/02-context管理.md", start: 43, end: 44, note: "compact 不是删历史，而是重建窗口身份" },
    { path: "docs/codex/03-memory实现.md", start: 5, end: 7, note: "memory 分成 phase1 / phase2" },
    { path: "docs/codex/04-存储与状态.md", start: 19, end: 27, note: "SQLite 重点表与各自职责" },
    { path: "docs/codex/05-调用链、压缩与边界.md", start: 25, end: 28, note: "memory startup 的主链路与适用条件" },
  ],
  contextDiagram: {
    title: "context 组成图",
    description: "codex 的上下文不是一次性拼好的，而是围绕 reference_context_item 做“首次全量、之后增量”。",
    nodes: [
      { title: "run_turn()", body: "每一轮从这里开始。" },
      { title: "reference_context_item", body: "决定本轮是全量还是增量。" },
      { title: "ContextManager normalize", body: "修正 turn 历史和 tool 对齐。" },
      { title: "build_initial_context()", body: "首次注入环境、权限、指令和人格。" },
      { title: "clone_history().for_prompt()", body: "生成最终 prompt 历史。" },
      { title: "model sampling", body: "用 window id 维持窗口身份。" },
    ],
  },
  lifecycleDiagram: {
    title: "memory 流程时间线",
    description: "memory 更像启动期后台流水线：先抽，再合，再同步，而不是每轮都直接写一个统一数据库。",
    nodes: [
      { title: "startup task", body: "只有满足条件才会启动。" },
      { title: "phase1 claim & extract", body: "先抢任务，再做抽取。" },
      { title: "stage1_outputs", body: "中间结果先落到 state DB。" },
      { title: "phase2 consolidation", body: "再做全局 consolidation。" },
      { title: "MemoryConsolidation agent", body: "统一整理长期记忆。" },
      { title: "memories/ + summary", body: "最后同步到文件系统和摘要入口。" },
    ],
  },
  storageDiagram: {
    title: "存储分层图",
    description: "state、logs、history 和 memories 分层得很清楚，不能混成一个“数据库”。",
    layers: [
      { title: "logs_2.sqlite", body: "日志层。" },
      { title: "state_5.sqlite", body: "线程、作业、stage1_outputs、spawn edges 等结构化运行态。" },
      { title: "history.jsonl", body: "全局 append-only 历史流。" },
      { title: "codex_home/memories/", body: "长期记忆文件同步层。" },
      { title: "memory_summary.md", body: "memory tool 的读取入口。" },
    ],
  },
  docLinks: [
    { label: "仓库入口页", path: "docs/codex.md" },
    { label: "01-架构与范围", path: "docs/codex/01-架构与范围.md" },
    { label: "02-context管理", path: "docs/codex/02-context管理.md" },
    { label: "03-memory实现", path: "docs/codex/03-memory实现.md" },
    { label: "04-存储与状态", path: "docs/codex/04-存储与状态.md" },
    { label: "05-调用链、压缩与边界", path: "docs/codex/05-调用链、压缩与边界.md" },
  ],
};
