export default {
  slug: "hermes-agent",
  name: "hermes-agent",
  docFolder: "hermes-agent",
  categoryLabel: "终端型 Agent Runtime",
  badgeText: "本地记忆 + provider 插件",
  plainIntro:
    "hermes-agent 是一个把 prompt 组装、会话持久化、context 压缩、内建 memory 和外部 provider memory 并行编排在一起的完整 agent runtime，而不是单一 memory 库。",
  summary:
    "它最关键的不是某一个 memory provider，而是把 prompt 组装、历史检索、内建记忆和外部 provider 记忆拆成并行链路，再由压缩点把会话切成新 session。",
  whatTheModelSees: [
    "模型入口不是“一个记忆层”，而是 prompt_builder 拼出的 system prompt 加上 turn 上下文。",
    "MEMORY.md / USER.md 这类内建 memory 会被加载、去重，并冻结进当前 prompt snapshot。",
    "session_search 只负责从 state.db 里的 transcript 历史检索，不等同于 long-term provider memory。",
    "ContextCompressor 不只是摘要，它还会先替换旧 tool 输出，再做结构化压缩。",
    "压缩时会保留头尾消息，并修复 tool call / result 的对齐关系。",
    "MemoryManager 把外部 provider 统一成可注册、可预取、可同步、可挂钩的插件层。",
    "压缩后的结果不是继续旧会话，而是重建 system prompt 并开启带 parent_session_id 的新 session。",
  ],
  contextBlocks: [
    { title: "system prompt assembly", summary: "prompt_builder 把身份、memory 指导、session_search 指导、skills、项目上下文和环境提示拼成 system prompt。", kind: "prompt" },
    { title: "project context references", summary: ".hermes.md/HERMES.md、AGENTS.md、CLAUDE.md、.cursorrules 以及 @file/@folder/@git/@diff/@url 会在发送前展开。", kind: "context-references" },
    { title: "compression engine", summary: "ContextCompressor 负责旧 tool 输出摘要、头尾保护、结构化压缩，以及 tool call / result 对齐修复。", kind: "compressor" },
    { title: "history retrieval", summary: "session_search 基于 state.db 中的 transcript 和 FTS5 检索，把命中的历史摘要回填到当前上下文。", kind: "retrieval" },
    { title: "session persistence", summary: "gateway/session 通过 JSONL + SQLite 双写保存轨迹。", kind: "storage" },
  ],
  assemblyFlow: [
    "run_agent 先初始化 MemoryStore、MemoryManager 和 ContextCompressor。",
    "prompt_builder 收集身份、memory 指导、session_search 指导、skills、项目上下文和环境提示，生成 system prompt。",
    "运行中再把 prefetch、tool dispatch、turn end 等节点串起来，持续补上下文。",
    "需要压缩时先 flush_memories()，再通知 provider 执行 on_pre_compress()。",
    "ContextCompressor.compress() 处理消息、工具输出和对齐修复后，重建 system prompt。",
    "旧 session 被结束，新的 session 以 parent_session_id 继续写回 state.db。",
  ],
  memoryLifecycle: [
    "启动时 MemoryStore 读取 HERMES_HOME/memories/MEMORY.md 和 USER.md，并做去重。",
    "内建 memory 会在会话开始时冻结成当前 system prompt snapshot。",
    "memory 工具只支持 add / replace / remove，写入前会扫 injection 和 exfil 风险。",
    "MemoryManager 统一注册外部 provider，并附加 provider prompt、prefetch、sync、tool schema 和生命周期钩子。",
    "各 provider 通过插件实现各自的 recall、profile、conclude 和 background sync 语义。",
    "需要刷新时，memory 先同步到 provider，再进入压缩与重建新 session 的循环。",
  ],
  storageLayers: [
    "state.db：SQLite 主库，承载 session、message、FTS5 和压缩后新 session 等元数据。",
    "sessions/<session_id>.jsonl：gateway 的会话镜像，用于双写、迁移和回放。",
    "HERMES_HOME/memories/：内建文件型 memory 根目录，存放 MEMORY.md 和 USER.md。",
    "supermemory.json / mem0.json / honcho.json / byterover/：外部 provider 的配置文件或本地工作目录。",
    "plugins/memory/*：各 provider 的实现层，封装 recall / sync / profile 能力。",
    "session_search：只读 state.db 的历史 transcript，不直接读 provider backend。",
  ],
  commonMistakes: [
    "把 session_search 当成 provider memory，导致历史检索和长期记忆混成一条链。",
    "把内建文件 memory 当成 transcript，忽略 MEMORY.md / USER.md 的快照属性。",
    "把 context compression 简化成“摘要”，忽略 tool 输出替换和 call / result 对齐修复。",
    "把外部 provider 当成单一实现，而不是可插拔并行层。",
    "误以为双写只是冗余备份，实际上它还承担迁移和异常恢复的连续性保障。",
  ],
  readerTakeaways: [
    "hermes-agent 的核心不是“记忆功能”，而是上下文、持久化和 provider 并行编排。",
    "要读懂它，先分清三条链：prompt 组装、历史检索、memory provider。",
    "压缩不是删信息，而是重建一次会话边界和 prompt lineage。",
  ],
  sourceAnchors: [
    { path: "docs/hermes-agent.md", start: 5, end: 5, note: "定义了它是完整 agent runtime，并点出 system prompt、session 持久化、long-term provider 这三条主干" },
    { path: "docs/hermes-agent.md", start: 29, end: 32, note: "概括了 memory、prompt_builder、session_search 和 provider 的并行关系" },
    { path: "docs/hermes-agent/01-架构与范围.md", start: 5, end: 9, note: "三条主干：prompt 组装、session 持久化、内建与外部 memory 编排" },
    { path: "docs/hermes-agent/01-架构与范围.md", start: 39, end: 41, note: "session_search 不是 provider memory，本地 memory 和外部 provider memory 也不是一回事" },
    { path: "docs/hermes-agent/02-context管理.md", start: 5, end: 5, note: "prompt_builder 如何把身份、memory、session_search、skills、项目上下文和环境提示拼进 system prompt" },
    { path: "docs/hermes-agent/02-context管理.md", start: 25, end: 25, note: "ContextCompressor 会先替换旧 tool 输出，再做结构化压缩和对齐修复" },
    { path: "docs/hermes-agent/02-context管理.md", start: 34, end: 34, note: "压缩后会 flush memories、重建 prompt、关闭旧 session 并创建新 session" },
    { path: "docs/hermes-agent/03-memory实现.md", start: 5, end: 5, note: "内建 memory 的真实落点是 HERMES_HOME/memories/MEMORY.md 和 USER.md" },
    { path: "docs/hermes-agent/03-memory实现.md", start: 23, end: 23, note: "MemoryManager 统一处理 provider 注册、prefetch、sync、tool schema 和生命周期钩子" },
    { path: "docs/hermes-agent/04-存储与状态.md", start: 5, end: 5, note: "state.db 承担 session、message、FTS5 和压缩后新 session 等元数据" },
    { path: "docs/hermes-agent/05-调用链、压缩与边界.md", start: 19, end: 21, note: "压缩主链会改变消息、prompt snapshot 和 session lineage" },
    { path: "docs/hermes-agent/05-调用链、压缩与边界.md", start: 38, end: 40, note: "session_search、内建 memory、provider memory 之间的边界" },
  ],
  contextDiagram: {
    title: "context 组成图",
    description: "它把 system prompt、历史检索、压缩和 provider 插件放成并行层，而不是一个统一大 memory。",
    nodes: [
      { title: "run_agent", body: "初始化 MemoryStore、MemoryManager 和 ContextCompressor。" },
      { title: "prompt_builder", body: "拼出 system prompt。" },
      { title: "ContextCompressor", body: "在需要时重写旧消息。" },
      { title: "session_search", body: "从 transcript 历史检索可用内容。" },
      { title: "MemoryManager", body: "调度 provider 插件。" },
      { title: "provider plugins", body: "各自 recall / sync / profile。" },
    ],
  },
  lifecycleDiagram: {
    title: "memory 流程时间线",
    description: "本地 memory、provider memory 和压缩重建会话是三条并行链，在 flush/compact 时合流。",
    nodes: [
      { title: "启动读取 memory", body: "先载入 MEMORY.md / USER.md。" },
      { title: "生成 system prompt", body: "把内建 memory 冻进当前快照。" },
      { title: "运行中检索/写入", body: "持续调 session_search 和 provider。" },
      { title: "flush_memories", body: "压缩前先把外部记忆同步出去。" },
      { title: "compress + rebuild", body: "重建 prompt 和消息视图。" },
      { title: "创建新 session", body: "以 parent_session_id 续接。" },
    ],
  },
  storageDiagram: {
    title: "存储分层图",
    description: "会话库、jsonl 镜像、文件型 memory 和 provider 配置层各司其职。",
    layers: [
      { title: "state.db", body: "核心会话库。" },
      { title: "sessions/*.jsonl", body: "轨迹镜像层。" },
      { title: "HERMES_HOME/memories/*.md", body: "文件型内建记忆。" },
      { title: "provider config", body: "外部 provider 的配置文件或工作目录。" },
      { title: "plugins/memory/*", body: "provider 实现层。" },
    ],
  },
  docLinks: [
    { label: "仓库入口页", path: "docs/hermes-agent.md" },
    { label: "01-架构与范围", path: "docs/hermes-agent/01-架构与范围.md" },
    { label: "02-context管理", path: "docs/hermes-agent/02-context管理.md" },
    { label: "03-memory实现", path: "docs/hermes-agent/03-memory实现.md" },
    { label: "04-存储与状态", path: "docs/hermes-agent/04-存储与状态.md" },
    { label: "05-调用链、压缩与边界", path: "docs/hermes-agent/05-调用链、压缩与边界.md" },
  ],
};
