export default {
  slug: "langmem",
  name: "langmem",
  docFolder: "langmem",
  categoryLabel: "Memory / Context 能力层",
  badgeText: "摘要节点 + BaseStore",
  plainIntro:
    "langmem 不是完整 agent，而是一套围绕 LangGraph / BaseStore 的短期摘要、长期 memory、反射执行和 namespace 隔离组件。",
  summary:
    "它更像可嵌入的 memory 能力层：短期上下文通过 RunningSummary 压缩，长期记忆通过 MemoryManager / BaseStore 写回，隔离和路由则交给 namespace 与 auth。",
  whatTheModelSees: [
    "模型主要看到的是消息流，而不是完整仓库状态；短期部分会被压成 running_summary 再继续参与推理。",
    "触发摘要时，旧消息会被压缩为新的 system message；SystemMessage 会被保留，相关 ToolMessage 也可能一起进入摘要。",
    "长期记忆不是直接暴露整个存储，而是通过 MemoryManager 结合 existing memories、schema 和抽取结果进入模型处理链。",
    "搜索记忆时，模型先生成 query，再由工具链去检索 memory，返回的是筛选后的候选结果。",
    "运行时可见的 namespace 来自 RunnableConfig[\"configurable\"]，同一套逻辑会映射到不同存储空间。",
    "后台反射不是前台主链的一部分，模型通常只感知处理结果。",
  ],
  contextBlocks: [
    { title: "短期摘要层", summary: "把历史消息压成可继续使用的 running_summary，控制上下文长度。", kind: "context" },
    { title: "长期 memory 层", summary: "从对话中抽取、更新、删除可持久化记忆。", kind: "memory" },
    { title: "搜索层", summary: "先生成 query，再从 memory store 检索相关候选。", kind: "retrieval" },
    { title: "运行时命名空间层", summary: "根据 RunnableConfig[configurable] 动态解析 namespace。", kind: "routing" },
    { title: "后台反射层", summary: "把 memory 处理延后到后台或远端执行。", kind: "execution" },
    { title: "存储与隔离层", summary: "长期状态落在注入式 BaseStore，并受 auth/namespace 约束。", kind: "storage" },
  ],
  assemblyFlow: [
    "读取 messages 和运行时配置，先解析 namespace 和当前上下文边界。",
    "summarize_messages() 或 SummarizationNode 先把旧消息压缩成 running_summary。",
    "MemoryManager 将对话文本与 existing memories 交给抽取器，产出新增、更新、删除候选。",
    "MemoryStoreManager 从 BaseStore 拉取候选 memory，再做整理、筛选和稳定定位。",
    "生成 final_puts / final_deletes，把结果写回 BaseStore。",
    "若启用异步链路，ReflectionExecutor 会把后续处理交给后台或远端 run。",
  ],
  memoryLifecycle: [
    "从对话中识别出值得保留的事实、偏好或任务状态。",
    "抽取器按 schema 生成 memory 候选，并结合已有记忆判断是新增、更新还是删除。",
    "通过稳定 ID 逻辑把同一条 memory 固定映射到同一位置。",
    "需要时经过 MemoryPhase 做额外整理，空结果则可由 default_factory 初始化。",
    "将最终变更整理成 final_puts / final_deletes。",
    "写入 BaseStore，下一轮通过搜索链路再次被召回或更新。",
  ],
  storageLayers: [
    "Graph state：保存短期运行态，例如 messages、running_summary、summarized_messages。",
    "Runtime config：RunnableConfig[configurable] 决定 namespace、线程和上下文参数。",
    "Namespace layer：NamespaceTemplate 把运行时变量拼成目标 namespace。",
    "Auth layer：graphs/auth.py 按身份重写或补全 namespace，做访问隔离。",
    "BaseStore layer：长期 memory 的真实落点由外部注入，仓库本身不自带本地 SQLite 或文件根。",
    "Background layer：ReflectionExecutor 负责把处理放到后台队列或远端 run 中。",
  ],
  commonMistakes: [
    "把 langmem 当成完整 agent runtime，而不是 memory/context 组件。",
    "把 running_summary 误认为长期记忆。",
    "硬编码 namespace，忽略 RunnableConfig[configurable] 的动态解析。",
    "以为仓库自带本地持久化存储，实际上真正后端是注入式 BaseStore。",
    "忽略消息 id，导致摘要去重和增量压缩出错。",
  ],
  readerTakeaways: [
    "先理解短期上下文，再看长期 memory，最后看存储与后台执行。",
    "langmem 的核心边界是“把记忆组件拆开组合”，不是“提供一个完整 agent”。",
    "真正值得记住的是：摘要归摘要，记忆归记忆，持久化归 BaseStore，隔离归 namespace/auth。",
  ],
  sourceAnchors: [
    { path: "docs/langmem.md", start: 5, end: 5, note: "仓库定位：LangGraph / BaseStore 上的 memory/context 工具库" },
    { path: "docs/langmem.md", start: 28, end: 31, note: "四个关键结论：摘要、长期 memory、namespace、反射执行" },
    { path: "docs/langmem/01-架构与范围.md", start: 5, end: 10, note: "四层模块分工" },
    { path: "docs/langmem/01-架构与范围.md", start: 21, end: 22, note: "不自带仓库级存储，依赖注入式 BaseStore" },
    { path: "docs/langmem/02-context管理.md", start: 5, end: 5, note: "summarize_messages() 的 token 预算与摘要插入规则" },
    { path: "docs/langmem/02-context管理.md", start: 14, end: 14, note: "RunningSummary 字段与去重压缩逻辑" },
    { path: "docs/langmem/03-memory实现.md", start: 5, end: 5, note: "MemoryManager 的抽取、更新、删除语义" },
    { path: "docs/langmem/03-memory实现.md", start: 22, end: 29, note: "MemoryStoreManager、稳定 ID 和写回控制" },
    { path: "docs/langmem/04-存储与状态.md", start: 14, end: 14, note: "NamespaceTemplate 从运行时配置解析 namespace" },
    { path: "docs/langmem/04-存储与状态.md", start: 22, end: 30, note: "ReflectionExecutor 与 auth 隔离" },
    { path: "docs/langmem/05-调用链、压缩与边界.md", start: 5, end: 7, note: "三条主调用链概览" },
  ],
  contextDiagram: {
    title: "context 组成图",
    description: "短期摘要、长期记忆检索和命名空间路由是三条同时作用的链。",
    nodes: [
      { title: "messages", body: "原始消息流。" },
      { title: "SummarizationNode", body: "先把旧消息压成 running_summary。" },
      { title: "MemoryManager", body: "抽取新增、更新、删除候选。" },
      { title: "MemoryStoreManager", body: "拉取并整理 store 里的候选记忆。" },
      { title: "NamespaceTemplate", body: "决定写到哪个空间。" },
      { title: "BaseStore", body: "长期记忆真实落点。" },
    ],
  },
  lifecycleDiagram: {
    title: "memory 流程时间线",
    description: "langmem 的 memory 更像图节点与 store 管理器的协作，而不是一个统一数据库动作。",
    nodes: [
      { title: "捕获消息", body: "先拿到 messages 和运行时配置。" },
      { title: "抽取候选 memory", body: "按 schema 生成候选。" },
      { title: "稳定 ID 定位", body: "判断新增、更新还是删除。" },
      { title: "final_puts / final_deletes", body: "整理最终变更集。" },
      { title: "写回 BaseStore", body: "把长期记忆持久化。" },
      { title: "下轮搜索召回", body: "通过 search tools 再拿回来。" },
    ],
  },
  storageDiagram: {
    title: "存储分层图",
    description: "短期状态、命名空间、隔离和长期存储分别属于不同层，不是同一块数据库。",
    layers: [
      { title: "Graph state", body: "messages、running_summary、summarized_messages。" },
      { title: "Runtime config", body: "configurable 决定线程与 namespace 参数。" },
      { title: "Namespace + auth", body: "负责路由和隔离。" },
      { title: "BaseStore backend", body: "长期记忆真正的后端。" },
      { title: "ReflectionExecutor", body: "后台或远端执行层。" },
    ],
  },
  docLinks: [
    { label: "仓库入口页", path: "docs/langmem.md" },
    { label: "01-架构与范围", path: "docs/langmem/01-架构与范围.md" },
    { label: "02-context管理", path: "docs/langmem/02-context管理.md" },
    { label: "03-memory实现", path: "docs/langmem/03-memory实现.md" },
    { label: "04-存储与状态", path: "docs/langmem/04-存储与状态.md" },
    { label: "05-调用链、压缩与边界", path: "docs/langmem/05-调用链、压缩与边界.md" },
  ],
};
