export default {
  slug: "letta",
  name: "letta",
  docFolder: "letta",
  categoryLabel: "平台型 Agent 系统",
  badgeText: "core memory + archive + Git-backed",
  plainIntro:
    "letta 把 agent 的核心块记忆、会话消息、归档记忆和 Git-backed 存储串成一条可重建的上下文链。",
  summary:
    "它最有代表性的地方是把 prompt 内可见的 core memory、会话消息、归档检索记忆和 Git-backed block 统一到同一平台模型里，但这几层仍然有清楚边界。",
  whatTheModelSees: [
    "模型先看到被编译好的 system prompt，其中包含 CORE_MEMORY、工具规则、来源目录和记忆元信息。",
    "标准模式下，核心记忆以 <memory_blocks> 呈现，带有 human、persona 等块、描述、字符上限和只读标记。",
    "Git 模式下，记忆会变成 <memory_filesystem> / <memory> / <self> 的路径化文件树，而不是平铺块。",
    "对话历史不是原始全量 transcript，窗口里只保留 system message、必要消息，以及可能插入的 summary message。",
    "available_skills 只在请求构建时注入，不会被长期持久化进 system prompt 存储。",
    "归档记忆通常不直接塞进 prompt，本体靠检索工具取回，模型先看到的是数量、标签和元信息。",
  ],
  contextBlocks: [
    { title: "AgentState", summary: "agent 的总状态容器，承载 system、memory、blocks、sources、tools、message_ids 和 compaction_settings。", kind: "状态容器" },
    { title: "Memory.compile", summary: "把 memory blocks、tool rules、sources 和文件块渲染成 LLM 可读的上下文文本。", kind: "上下文渲染" },
    { title: "PromptGenerator metadata", summary: "为 system prompt 追加 AGENT_ID、CONVERSATION_ID、消息数和归档规模。", kind: "提示注入" },
    { title: "Conversation system message", summary: "每个 conversation 都有自己持久化的 system message，位置 0，由当前 memory 重新编译得到。", kind: "会话固化" },
    { title: "ContextWindowCalculator", summary: "按 token 预算拆出 system、memory、summary、messages、tools 等部分。", kind: "窗口评估" },
    { title: "Git / Archive storage", summary: "核心块和归档记忆分别走 git-backed blocks、SQL passages 和可选向量库检索。", kind: "持久化与检索" },
  ],
  assemblyFlow: [
    "创建或更新 agent 时，先整理 memory_blocks、tags、sources 和 compaction_settings。",
    "需要 Git-backed memory 时，把块标签转成路径化标签，再创建或回填 memfs repo。",
    "PromptGenerator.compile_system_message_async() 调 Memory.compile()，把核心记忆、工具规则和来源目录装进 system prompt。",
    "ConversationManager 把这份 system message 持久化为 conversation 的第 0 条消息，并写入 conversation_messages。",
    "ContextWindowCalculator 再把 system、memory、files、summary、messages 和 tools 拆开计 token，判断当前窗口占用。",
    "一旦窗口压力过大，Summarizer 会压缩旧消息，插入 summary message，再继续后续轮次。",
  ],
  memoryLifecycle: [
    "块先以 label/value/limit/read_only/description/metadata 的形式存在，默认核心块是 human 和 persona。",
    "Git 模式下，块会被序列化成 Markdown + YAML frontmatter，落到 ~/.letta/memfs/{org_id}/{agent_id}/repo.git。",
    "写入流程是 git 先行、Postgres 缓存随后同步；启用 Git-backed memory 时还支持 repo 缺失回填。",
    "记忆块变更后，系统会重编译 prompt，并重写 conversation 的 system message。",
    "运行时新增长期记忆会进入 archive/passage：先写 SQL，再按需双写到向量后端。",
    "检索时根据 embedding、标签和时间范围搜索归档记忆，把结果作为工具返回给模型。",
  ],
  storageLayers: [
    "记忆块层：Memory.blocks / Block，负责模型当前可见的核心记忆。",
    "会话层：messages + conversation_messages，负责当前 conversation 的消息顺序和 system message 归属。",
    "Git 层：memfs repo 和 Markdown 文件，负责 Git-backed block 的版本历史。",
    "缓存层：PostgreSQL，负责快速读写和与 git 状态同步。",
    "归档层：Archive / Passage 的 SQL 存储，负责长期记忆主体。",
    "向量层：可选 Turbopuffer / embedding 检索，负责归档记忆的语义搜索。",
  ],
  commonMistakes: [
    "把 conversation_messages 当成完整真相，而忽略 system message 会被重编译并固定在位置 0。",
    "把 Git-backed memory 误解成“替代数据库”，其实它是 git 真源 + Postgres 缓存的双层结构。",
    "把核心记忆块和归档记忆混成一类，前者进 prompt，后者靠检索工具取回。",
    "把 available_skills 当成持久记忆；它是请求期注入，不会长期存储在 prompt 里。",
    "把 summary message 当成真实用户消息；它是压缩历史时插入的占位消息。",
  ],
  readerTakeaways: [
    "先分清三层：prompt 内可见的 core memory、会话消息、归档检索记忆。",
    "再分清两条路径：标准块渲染 vs Git-backed 文件树渲染。",
    "最后盯住重编译点：块改了、会话开了、窗口满了，就会触发 prompt / summary / storage 的联动。",
  ],
  sourceAnchors: [
    { path: "docs/letta.md", start: 5, end: 5, note: "总览 AgentState.memory/blocks、MessageManager、ArchiveManager、Git-backed memory 四块主线" },
    { path: "docs/letta.md", start: 30, end: 30, note: "说明 system prompt、Memory.compile、ContextWindowCalculator、archive/passage、BlockManager 的关系" },
    { path: "docs/letta/01-架构与范围.md", start: 5, end: 12, note: "定义 letta 的四个核心域：AgentState、消息/会话、归档、Git-backed memory" },
    { path: "docs/letta/02-context管理.md", start: 3, end: 7, note: "AgentState 的字段范围，包含 message_ids、system、memory、blocks、sources、tools、compaction_settings" },
    { path: "docs/letta/02-context管理.md", start: 11, end: 17, note: "Memory.compile 的渲染入口与标准/line-numbered 分支" },
    { path: "docs/letta/02-context管理.md", start: 28, end: 32, note: "ConversationManager 负责 system message 的编译、持久化和 conversation 绑定" },
    { path: "docs/letta/02-context管理.md", start: 36, end: 40, note: "ContextWindowCalculator 和 Summarizer 的配合关系" },
    { path: "docs/letta/03-memory实现.md", start: 5, end: 9, note: "Block / Memory 的字段结构，human 与 persona 是默认核心块" },
    { path: "docs/letta/03-memory实现.md", start: 13, end: 18, note: "Markdown + YAML frontmatter、memfs 路径和 repo 结构" },
    { path: "docs/letta/03-memory实现.md", start: 22, end: 34, note: "GitEnabledBlockManager 的 source of truth / cache、archive / passage dual-write" },
  ],
  contextDiagram: {
    title: "context 组成图",
    description: "letta 先编译 memory，再把它固化成会话的 system message，然后才去计算当前窗口。",
    nodes: [
      { title: "AgentState", body: "总状态容器。" },
      { title: "Memory.compile", body: "把块记忆渲染成模型可读文本。" },
      { title: "PromptGenerator", body: "补上 agent / conversation 元信息。" },
      { title: "system message", body: "作为会话第 0 条消息固定下来。" },
      { title: "ContextWindowCalculator", body: "再评估窗口预算。" },
      { title: "Summarizer", body: "窗口过大时插入 summary message。" },
    ],
  },
  lifecycleDiagram: {
    title: "memory 流程时间线",
    description: "核心块记忆、Git-backed 持久化和 archive 检索并不是一条线，而是在重编译点相互联动。",
    nodes: [
      { title: "Block 创建/更新", body: "先改核心块。" },
      { title: "Git serialize", body: "Git 模式下写成 Markdown + frontmatter。" },
      { title: "Postgres cache", body: "同步缓存当前状态。" },
      { title: "System prompt rebuild", body: "重编译 core memory。" },
      { title: "Conversation message 0", body: "更新会话里的 system message。" },
      { title: "Archive search", body: "长期记忆走工具检索返回。" },
    ],
  },
  storageDiagram: {
    title: "存储分层图",
    description: "prompt 可见层、会话层、Git 真源层、缓存层和归档层都不同。",
    layers: [
      { title: "Memory.blocks", body: "prompt 可见的核心块记忆。" },
      { title: "conversation_messages", body: "当前会话的 system 和消息顺序。" },
      { title: "memfs repo", body: "Git-backed block 的版本真源。" },
      { title: "Postgres", body: "快速读写与同步缓存。" },
      { title: "Archive SQL", body: "长期归档记忆主体。" },
      { title: "Vector DB", body: "语义检索层。" },
    ],
  },
  docLinks: [
    { label: "仓库入口页", path: "docs/letta.md" },
    { label: "01-架构与范围", path: "docs/letta/01-架构与范围.md" },
    { label: "02-context管理", path: "docs/letta/02-context管理.md" },
    { label: "03-memory实现", path: "docs/letta/03-memory实现.md" },
    { label: "04-存储与状态", path: "docs/letta/04-存储与状态.md" },
    { label: "05-调用链、压缩与边界", path: "docs/letta/05-调用链、压缩与边界.md" },
  ],
};
