export default {
  slug: "mem0",
  name: "mem0",
  docFolder: "mem0",
  categoryLabel: "Memory / Context 能力层",
  badgeText: "抽取式长期记忆",
  plainIntro:
    "mem0 是一个围绕“抽取式长期记忆”设计的 Memory / AsyncMemory 层，把近期消息、已有记忆、实体链接和历史审计串成一套可检索、可更新的记忆系统，而不是完整的对话运行时。",
  summary:
    "它最重要的特点是：长期记忆主体在向量库，SQLite 只是短窗上下文与审计辅助层；因此你不能把 history/messages 当成真正的 memory 本体。",
  whatTheModelSees: [
    "session_scope 作为隔离边界，决定这一轮抽取/写入能看见哪一组消息和记忆。",
    "最近 10 条消息会被拉出来，和新消息一起形成“抽取上下文”。",
    "最近 10 条已有 memories 会参与检索与去重，防止重复写入。",
    "parse_messages / parse_vision_messages 会把消息扁平化成统一文本输入，视觉内容先转成描述。",
    "generate_additive_extraction_prompt 会把 Summary、Last k Messages、Recently Extracted Memories、Existing Memories、New Messages、日期和自定义指令拼进去。",
    "只有 agent_id 而没有 user_id 时，会追加 AGENT_CONTEXT_SUFFIX，把抽取视角切到 agent 视角。",
    "search 阶段看到的是混合检索输入：语义向量、关键词/BM25、实体命中和可选 rerank 结果。",
  ],
  contextBlocks: [
    { title: "仓库定位", summary: "mem0 的核心是 Memory / AsyncMemory，围绕抽取式长期记忆工作，不是完整 chat runtime。", kind: "定位" },
    { title: "上下文窗口", summary: "抽取时只看 session_scope 内最近 10 条消息，并结合最近 10 条已有 memories。", kind: "上下文" },
    { title: "抽取输入", summary: "上下文会被拼成 additive extraction prompt，包含 Summary、Last k、Existing、New、日期和自定义指令。", kind: "输入" },
    { title: "写入主链路", summary: "add() 会先抽取，再去重、embedding、写向量库，同时落 SQLite history/messages，并更新实体链接。", kind: "流程" },
    { title: "存储分层", summary: "长期记忆主体在 vector store，SQLite 只负责 history/messages，entity store 单独保存实体到 memory 的关联。", kind: "存储" },
  ],
  assemblyFlow: [
    "先校验 user_id / agent_id / run_id 和 memory_type，并把消息与 metadata 规范化。",
    "按 session_scope 取最近 10 条消息，再检索 top 10 现有 memories 作为上下文。",
    "组装 additive extraction prompt；如果是 agent-only 场景，再追加 agent 视角后缀。",
    "调 LLM 做一次抽取，解析 JSON 结果，拿到候选 memories。",
    "对候选结果做 hash 去重、embedding，并写入 vector store。",
    "同步写 SQLite history/messages；再根据实体结果更新或插入 entity store 里的链接。",
  ],
  memoryLifecycle: [
    "输入消息先被规范化，必要时先做视觉描述或文本扁平化。",
    "进入抽取阶段后，系统会生成候选 memory，或者在 procedural_memory 分支里直接产出总结式记忆。",
    "候选 memory 被去重、编码、写入向量库，成为长期记忆主体。",
    "同步生成 history 记录，并把近期消息留在 SQLite 的 messages 窗口里。",
    "搜索时，系统会综合语义、关键词、实体和 rerank 结果，返回可读记忆。",
    "更新和删除会保留历史轨迹；reset() 则直接清掉历史表、消息表和向量存储。",
  ],
  storageLayers: [
    "vector store：长期记忆主体，保存 memory 本体、hash、时间戳、lemmatized text 和检索索引。",
    "entity store：独立 collection，保存实体文本、类型和 linked_memory_ids。",
    "SQLite history：记录 add / update / delete 的审计轨迹，不是长期记忆本体。",
    "SQLite messages：只保留每个 session_scope 最近 10 条消息，作为抽取上下文。",
    "local state：MEM0_DIR、config.json 和 history.db 组成本地状态根目录。",
    "provider-backed storage：向量库后端由 factory 和 provider config 决定。",
  ],
  commonMistakes: [
    "把 history/messages 当成长期记忆本体，实际上它们只是辅助上下文和审计。",
    "在 search() 里没带 user_id / agent_id / run_id，会直接触发过滤校验失败。",
    "以为 AsyncMemory 是另一套逻辑，实际上只是同步逻辑的异步包装。",
    "以为 mem0 内置了完整 conversation compaction 主线，其实没有统一压缩流程。",
    "忽略 agent_id 单独出现时的 agent 视角后缀，导致抽取视角和预期不一致。",
  ],
  readerTakeaways: [
    "mem0 的核心价值是“把短期消息抽成可检索的长期记忆”，不是把对话全文一直塞进上下文。",
    "真正的长期记忆主体在向量库，SQLite 主要服务于历史和短窗上下文。",
    "理解 session_scope、抽取 prompt 和 entity linking，就基本理解了 mem0 的主设计。",
  ],
  sourceAnchors: [
    { path: "docs/mem0.md", start: 22, end: 27, note: "总结仓库定位：context 不是长对话缓存，memory 至少三层，Sync/Async 只是包装差异" },
    { path: "docs/mem0/01-架构与范围.md", start: 3, end: 19, note: "主模块清单：Memory/AsyncMemory、storage、utils、prompts、factory" },
    { path: "docs/mem0/01-架构与范围.md", start: 29, end: 39, note: "明确 context 不是 runtime，SQLite 不是 long-term memory，vector store + entity store 才是主体" },
    { path: "docs/mem0/02-context管理.md", start: 3, end: 18, note: "session_scope 与最近 10 条消息窗口" },
    { path: "docs/mem0/02-context管理.md", start: 20, end: 44, note: "扁平化上下文、抽取 prompt、agent-scoped suffix" },
    { path: "docs/mem0/03-memory实现.md", start: 3, end: 20, note: "写入主链路、去重 payload 与 hash" },
    { path: "docs/mem0/03-memory实现.md", start: 22, end: 47, note: "search 的混合检索、entity store、procedural memory、history" },
    { path: "docs/mem0/04-存储与状态.md", start: 3, end: 41, note: "MEM0_DIR/history_db_path、SQLite 两表、向量库路径、entity collection" },
    { path: "docs/mem0/05-调用链、压缩与边界.md", start: 3, end: 49, note: "add/search/AsyncMemory/compaction 边界" },
  ],
  contextDiagram: {
    title: "context 组成图",
    description: "mem0 的上下文是为“抽取长期记忆”服务的，不是完整会话 runtime 的上下文窗口。",
    nodes: [
      { title: "消息输入", body: "先规范化消息和 metadata。" },
      { title: "session_scope", body: "确定当前隔离边界。" },
      { title: "最近 10 条消息", body: "形成短窗上下文。" },
      { title: "最近 10 条 memories", body: "用于去重和参考。" },
      { title: "抽取 prompt", body: "拼成 additive extraction prompt。" },
      { title: "记忆写入", body: "把候选 memory 写入长期层。" },
    ],
  },
  lifecycleDiagram: {
    title: "memory 流程时间线",
    description: "真正的长期记忆不是对话历史，而是抽取、去重、编码后写进向量库的结果。",
    nodes: [
      { title: "规范化输入", body: "把文本和视觉消息统一化。" },
      { title: "上下文收集", body: "取最近消息和已有 memory。" },
      { title: "抽取 / 总结", body: "让 LLM 产出候选记忆。" },
      { title: "去重与 embedding", body: "先判重再编码。" },
      { title: "写入向量库", body: "形成长期记忆主体。" },
      { title: "history / entity linking", body: "补齐审计与实体索引。" },
    ],
  },
  storageDiagram: {
    title: "存储分层图",
    description: "主记忆在向量库，entity store 是索引层，SQLite 是辅助层。",
    layers: [
      { title: "L1 向量库", body: "主记忆本体。" },
      { title: "L2 entity store", body: "实体索引层。" },
      { title: "L3 SQLite history", body: "审计轨迹。" },
      { title: "L4 SQLite messages", body: "最近 10 条上下文。" },
      { title: "L5 本地状态", body: "MEM0_DIR/config.json/history.db。" },
    ],
  },
  docLinks: [
    { label: "仓库入口页", path: "docs/mem0.md" },
    { label: "01-架构与范围", path: "docs/mem0/01-架构与范围.md" },
    { label: "02-context管理", path: "docs/mem0/02-context管理.md" },
    { label: "03-memory实现", path: "docs/mem0/03-memory实现.md" },
    { label: "04-存储与状态", path: "docs/mem0/04-存储与状态.md" },
    { label: "05-调用链、压缩与边界", path: "docs/mem0/05-调用链、压缩与边界.md" },
  ],
};
