version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions-nonbreaking:
        applies-to: "version-updates"
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "actions/checkout"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "actions/setup-node"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "actions/configure-pages"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "actions/upload-pages-artifact"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "actions/deploy-pages"
        update-types:
          - "version-update:semver-major"
